#pragma once

#define SYS_EXIT          1
#define SYS_READ          2
#define SYS_WRITE         3
#define SYS_OPEN          4
#define SYS_CLOSE         5
#define SYS_CREAT         6
#define SYS_UNLINK        7
#define SYS_CHDIR         8
#define SYS_LSEEK         9
#define SYS_RENAME        10
#define SYS_MKDIR         11
#define SYS_RMDIR         12
#define SYS_REBOOT        13
#define SYS_STAT          14
#define SYS_POWEROFF      15
#define SYS_SLEEP         16
#define SYS_READDIR       17
#define SYS_OPENDIR       18
#define SYS_CLOSEDIR      19
#define SYS_GETCWD        20
#define SYS_SYNC          21
#define SYS_TRUNC         22
#define SYS_TERMCTL       23
#define SYS_CREATEFB      24
#define SYS_RMFB          25
#define SYS_SWITCHFB      26
#define SYS_CLEARFB       27
#define SYS_FLUSHSCR      28
#define SYS_GETFBINF      29
#define SYS_GETFBTYP      30
#define SYS_GETCURFB      31
#define SYS_GETTIMEOFDAY  32
#define SYS_GETMTIMEOFDAY 33
#define SYS_GETTIMEMONOMS 34
#define SYS_GETTIMEMONO   35
#define SYS_MMAP          36
#define SYS_MUNMAP        37
#define SYS_GETRAWSC      38
#define SYS_CREATEFBWMEM  39
#define SYS_RMFBWMEM      40
#define SYS_GETMOUSEINFO  41
#define SYS_NEWPROC       42
#define SYS_WAIT          43
#define SYS_KILL          44
#define SYS_GETPID        45
#define SYS_GETUID        46
#define SYS_SETUID        47
#define SYS_GETGID        48
#define SYS_SETGID        49
#define SYS_GETEUID       50
#define SYS_SETEUID       51
#define SYS_GETEGID       52
#define SYS_SETEGID       53

void init_syscalls();
